---

- name: Get current php version
  become: yes
  shell: source /etc/profile && phpbrew list | grep "*" | awk -F- '{print $2;}' | sed 's/^[ \t]*//;s/[ \t]*$//'
  args:
    executable: /bin/bash
  register: phpbrew_current_output
  changed_when: False
  always_run: yes

- name: Register phpbrew fact current
  set_fact:
    php_current_used_version: "{{ phpbrew_current_output.stdout }}"
    cacheable: yes

- name: Get latest php version
  become: yes
  shell: source /etc/profile && phpbrew list | sort  -n -t. -r +1 +2 +3 | head -n 1 | awk -F- '{print $2;}' | sed 's/^[ \t]*//;s/[ \t]*$//'
  args:
    executable: /bin/bash
  register: phpbrew_list_output
  changed_when: False
  always_run: yes

- name: Register phpbrew fact
  set_fact:
    php_version: "{{ phpbrew_list_output.stdout }}"
    cacheable: yes


- name: Switch php version
  become: yes
  shell: source /etc/profile; phpbrew switch "{{php_version}}"
  args:
    executable: /bin/bash
  when: php_version > php_current_used_version

- set_fact:
    php_socket: /opt/phpbrew/php/php-{{php_version}}/var/run/php-fpm.sock

- name: Update php-fpm config
  become: yes
  template:
    src: php-fpm.conf.j2
    dest: /opt/phpbrew/php/php-{{php_version}}/etc/php-fpm.conf
    owner: root
    group: root
    mode: 0644
  notify: php reload

- name: Update php-www config
  become: yes
  template:
    src: www.conf.j2
    dest: /opt/phpbrew/php/php-{{php_version}}/etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
  notify: php reload

- name: Update php.ini config
  become: yes
  template:
    src: php.ini.j2
    dest: /opt/phpbrew/php/php-{{php_version}}/etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify: php reload

- shell: cat /lib/systemd/system/phpbrew-fpm.service | grep PIDFile |  grep -q php-"{{php_version}}"
  become: yes
  args:
    executable: /bin/bash
  changed_when: false
  ignore_errors: yes
  register: php_check_service_file_result

- file:
    path: /lib/systemd/system/phpbrew-fpm.service
    state: absent
  when: php_check_service_file_result.rc != 0
  become: yes

- name: Create systemd
  become: yes
  shell: source /etc/profile; phpbrew use "{{php_version}}"; phpbrew fpm setup --systemctl php-"{{php_version}}"
  args:
    executable: /bin/bash
    creates: /lib/systemd/system/phpbrew-fpm.service
  notify: php reload  
  register: systemd_php_unit

- systemd: 
    daemon_reload: yes
  when: systemd_php_unit.changed
  become: yes

- name: Enable systemd service
  become: yes
  service:
    name: phpbrew-fpm
    enabled: yes
    state: started

- name: Update nginx config
  become: yes
  template:
    src: nginx-upstream.conf.j2
    dest: /etc/nginx/conf.d/01-upstream.conf
    owner: root
    group: root
    mode: 0644
  notify: nginx reload
 

