---

- debug: msg="{{extension_dir}}/{{extension}}.so"

- name: "Install extensions {{extension}}"
  become: yes
  shell: "source /etc/profile && export CCACHE_DIR=$(realpath ~/.ccache) && export PATH=/usr/lib/ccache:$PATH &&  phpbrew ext install {{extension}}"
  args:
    executable: /bin/bash
    chdir: /opt/phpbrew/
    creates: "{{extension_dir}}/{{extension}}.so"
  notify: php restart
