---
# tasks file for php

- name: Prepare to phpbrew
  import_tasks: preinstall.yml

- name: phpbrew compile
  import_tasks: compile.yml

- name: php configure
  import_tasks: configure.yml

- shell: source /etc/profile; phpbrew path bin;
  args:
    executable: /bin/bash
  become: yes
  register: php_path_bin_result
  changed_when: false

- name: set php path
  set_fact:
    php_cli: "{{php_path_bin_result.stdout}}/php"
    cacheable: yes
  changed_when: false

- name: composer
  import_tasks: composer.yml

