---
# handlers file for php

- name: php reload
  become: yes
  service:
    name: phpbrew-fpm
    state: reloaded

- name: nginx reload
  become: yes
  service:
    name: nginx
    state: reloaded
  ignore_errors: true

